### PR TITLE
Revert installed package versions respect .nvmrc

### PR DESCRIPTION
**Pull request by tiffon**
New version of react-scripts requires node >= v6. Reverting react-scripts and several eslint related packages to respect the `.nvmrc` of `4`.

### CODE REVIEW

**Comment by saminzadeh** [comment]
I'm ok upgrading.
Node 4 was the min version create-react-app supported at the time.

**Comment by tiffon** [comment]
>I'm ok upgrading.
>Node 4 was the min version create-react-app supported at the time.

Oh man! Forgot we build this locally then commit the bundled files! Nice (sort of)!

**Comment by saminzadeh** [comment]
We don't commit locally. We just need to make sure whatever process is doing the build has Node >= 4

**Comment by tiffon** [comment]
Closing as building on node >= 6 is fine.

**Pull request closed without merging**
